package semesters.fourth.lab4.enums;

public enum ErrorType {
    INCORRECT_INPUT_DATA,
    INCORRECT_COMMAND,
    INCORRECT_COUNT_PARAMS,
    INCORRECT_PRICE_OR_PRICE_FORMAT,
    NOT_DATA,
    INCORRECT_TRANSACTION,
    FAIL_EXECUTION,
    FAIL_CLOSE_CONNECTION_WITH_DB,
    INPUT_ERROR,
}
